server:
  port: 8081
  servlet:
    context-path: /api/v0/auth

spring:
  application:
    name: mcsv-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL del servidor Eureka
    fetch-registry: true  # Indica si debe obtener la lista de instancias de Eureka
    register-with-eureka: true  # Indica si debe registrarse en Eureka